version: '3.8'

services:
  vnstock-collector:
    build: .
    container_name: vnstock-data-collector
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vnstock-network

networks:
  vnstock-network:
    driver: bridge
